### ISSUE TITLE
New Warning: 7th Penalty = FO Column Entry

### ISSUE THREAD

**Issue by official-sounding** [AdamSmasherDerby/Statsbook-Tool#12]
Was reviewing a statsbook this weekend and ran across the following situation: for two foul-out cases, the code in the 7th penalty box was entered in the "FO/EXP" column.  I think it makes sense to add this as a warning case, but wanted to double-check before just going and doing it.

Obviously, in occasional cases a skater can be expelled on their 7th penalty (so this shouldn't be an error), but in most cases, this is probably an incorrect entry, and is likely something that would get a statsbook bounced back in a sanctioned situation.

**Comment by AdamSmasherDerby** [comment]
Good idea.  Added in 318f564f3c1cacf787fdd2fc8add17916f01d26a
