### ISSUE TITLE
Suggestion for another check - IGRF, expulsion/suspension markers

### ISSUE THREAD

**Issue by redhillian** [AdamSmasherDerby/Statsbook-Tool#14]
Check that the "suspension" box on the IGRF tab (cell L7) has been marked as either "yes" or "no" (from YES|NO), and if "Yes", has at least one summary been entered in A41 (and corresponding suspension marker in L41); or suspension served in F40

L7 should be actively marked regardless of expulsion happening - should be at NO unless expulsion & suspension recommended, or suspension served.

**Comment by AdamSmasherDerby** [comment]
Per the statsbook manual,  L7 should be left blank unless there was an expulsion during the game.

That said, I COULD implement a check to ensure that "suspension" is entered yes or no when there IS an expulsion is marked on the PT sheet, as well as there being _something_ in the expulsion boxes in that case.

I do wonder, though - with the IGRF itself required to be scanned, and likely filled out by hand before that, it is necessary to be picky about the electronic copy?  I'll check with Stabby and see what she thinks.

**Comment by redhillian** [comment]
Huh; statsbook manual disagrees with the on page notes for the IGRF: The
notes for L7 on the sheet itself say

"Mark YES if a Suspension is  recommended for one or more Skaters -- and
include scanned signed Expulsion-Suspension Form(s), with scanned IGRF.
Also mark YES if a Suspension is being served in this game.

Otherwise, mark NO."

I'll take that to WFTDA's bug reports then, and not yours!

**Comment by AdamSmasherDerby** [comment]
That IS interesting.

Stabby says that since the _scanned_ IGRF is mostly what gets looked at, and the electronic one is primarily used to generate the paper copy and populate the rest of the statsbook, she doesn't think it's really necessary to check the electronic one too carefully to make sure it's got these updated.  I think I'll leave this one on the back burner for now.

**Comment by redhillian** [comment]
Fair. Have also sent timeout an issue that the instructions don't match!
