### ISSUE TITLE
Incorrect Lost lead checked without a corresponding penalty

### ISSUE THREAD

**Issue by quietriotchatt** [AdamSmasherDerby/Statsbook-Tool#23]
I used the Statsbook Tool on a statsbook exported from the CRG scoreboard version 2023.5. It found 14 instances of "Lost lead checked without a corresponding penalty". When I checked the penalty stats, I found that to be true for only 4 of the instances. I'm attaching the excel file that was exported from the scoreboard.
[STATS-2024-03-30_ChattanoogaAllStars_vs_AtlantaDirtySouthDerby.xlsx](https://github.com/AdamSmasherDerby/Statsbook-Tool/files/14816884/STATS-2024-03-30_ChattanoogaAllStars_vs_AtlantaDirtySouthDerby.xlsx)

**Comment by AdamSmasherDerby** [comment]
EDIT:  I think I buried the lede here.  Just open the statsbook in Excel and then save it, and it will work.

This is a known issue with Excel, and not something we can fix.  The statsbook is full of Excel formulas that do things like move the skater numbers from the IGRF page to the Lineups and Penalties page.

So for example, the first skater on the penalty list in a default statsbook is "=IF(IGRF!B14="","",IGRF!B14)".

When you open Excel, it goes through and calculates all those values, and stores them in the "value" attribute for each cell. Once you save the spreadsheet, all those values are saved.

But an exported spreadsheet from CRG has never been calculated, and it's not possible to make CRG do that. (see: https://github.com/rollerderby/scoreboard/issues/601)

So the only solution is to open and then save the statsbook before importing it to the checker.

What I CAN do is make a note to future me to do a CHECK for this issue - if the first skater on the penalty tab is blank, throw a warning that the spreadsheet may not have been calculated yet.

Hey future me!  Look into this.

**Comment by AdamSmasherDerby** [comment]
Check added in [v3.2.0](https://github.com/AdamSmasherDerby/Statsbook-Tool/tree/v3.2.0). Should now warn when uncalculated statsbook is loaded.
