### ISSUE TITLE
Warns of Previously Penalized Skater Not on Lineup When No Penalty Was Recorded for the skater

### ISSUE THREAD

**Issue by vcorneau** [AdamSmasherDerby/Statsbook-Tool#24]
Skater's 2 penalties are marked in the penalty tab and correspond to penalties on lineup. 

Warns of missing skater on lineup for 8 additional lines where no penalty was marked. 
![image](https://github.com/AdamSmasherDerby/Statsbook-Tool/assets/5306456/bf83ff12-17e5-4531-ba0e-91f39671420b)

**Comment by AdamSmasherDerby** [comment]
Can you please post here or PM me the statsbook file that you believe is generating incorrect messages?

**Comment by vcorneau** [comment]
[image: Excel Spreadsheet]
STATS-2024-06-08_Hammer City…
<https://docs.google.com/file/d/13EwDV59NRee9x3Sl4wzwEG7Mv3gih4Ts/edit?usp=docslist_api&filetype=msexcel>
Absolutely - here it is

*Virginie Corneau*
[ They / Them / Iel ]

**Comment by AdamSmasherDerby** [comment]
The software appears to be functioning as intended. On the lineup tab, in period 1, Jam 19, skater 721 for Black is shown as sitting with a "-" code.  However, they must have left the box at SOME point.  So there's some error here - if they left the box in that jam, the code should be "+", and if they didn't then either they should be on the lineup in the subsequent jam, or some other skater should have been indicated as a substitute by starting the next jam in the box.

Replacing the "-" with a "+" clears all the errors.
