### ISSUE TITLE
Warns of Skater Previously seated in Box when no penalty marked for skater on lineup or penalty tab

### ISSUE THREAD

**Issue by vcorneau** [AdamSmasherDerby/Statsbook-Tool#25]
No penalty listed for skater on lineup or penalty tabs for that jam. 
![image](https://github.com/AdamSmasherDerby/Statsbook-Tool/assets/5306456/d5c4e44a-4cd5-4bf9-8b88-2607f1c1ec98)

**Comment by AdamSmasherDerby** [comment]
Same comment as the other thread - can you please send me a Statsbook file that is causing your issues?

**Comment by AdamSmasherDerby** [comment]
(same comment as other thread)

The software appears to be functioning as intended. On the lineup tab, in period 1, Jam 19, skater 721 for Black is shown as sitting with a "-" code.  However, they must have left the box at SOME point.  So there's some error here - if they left the box in that jam, the code should be "+", and if they didn't then either they should be on the lineup in the subsequent jam, or some other skater should have been indicated as a substitute by starting the next jam in the box.

Replacing the "-" with a "+" clears all the errors.
