### ISSUE TITLE
ᚾ character in Lineup sheets

### ISSUE THREAD

**Issue by frank-weinberg** [AdamSmasherDerby/Statsbook-Tool#5]
I have just come across a statsbook where the ᚾ character was used in the boxes where that notation was used on the original sheet. (I tried attaching it, but that failed.) This threw off the tool:

- It was reported as "Skater previously seated in box with no code on present line" but not for the jam with the ᚾ character but the next jam after that in which the respective player was fielded and not in the box.
- In addition there were reports of "Penalzied skater not on lineup" for every jam inbetween the one with the ᚾ character and the one reported as "Skater previously seated in box with no code on present line" (excluding ones in which the skater was fielded and in the box).

Expected behaviour: The tool should either report the wrong character in the correct jam or accept it as an alternative notation (maybe with a warning).

**Comment by AdamSmasherDerby** [comment]
Given that I have heard of statsbooks being rejected by the higher powers for using the character, I'll add it as an error.

**Comment by frank-weinberg** [comment]
That's also good to know given that I received that statsbook as such a higher power in a more local context. :)

**Comment by AdamSmasherDerby** [comment]
Resolved by https://github.com/AdamSmasherDerby/Statsbook-Tool/commit/9ce867c89e5ca8197cf123b416c311e8016b84b7
